'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourceForPDF
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.ResourceForPDF", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to נטיות תעסוקתיות.
        '''</summary>
        Friend Shared ReadOnly Property chapter1Bookmark() As String
            Get
                Return ResourceManager.GetString("chapter1Bookmark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המלצה לרמת לימוד.
        '''</summary>
        Friend Shared ReadOnly Property chapter2Bookmark() As String
            Get
                Return ResourceManager.GetString("chapter2Bookmark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המלצה למסלולי לימוד.
        '''</summary>
        Friend Shared ReadOnly Property chapter3Bookmark() As String
            Get
                Return ResourceManager.GetString("chapter3Bookmark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המלצה למקצועות מתאימים.
        '''</summary>
        Friend Shared ReadOnly Property chapter4Bookmark() As String
            Get
                Return ResourceManager.GetString("chapter4Bookmark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חוות הדעת של .
        '''</summary>
        Friend Shared ReadOnly Property chavat() As String
            Get
                Return ResourceManager.GetString("chavat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to איך הכנתי עבורך את הדוח:
        '''הדוח אסף את המרכיבים שעלו באבחון ומפרט אותם כך שניתן יהיה באופן פשוט לבנות את תוכנית הקריירה האישית שלך.
        '''הפרק האישיותי - בפרק זה נציג את מרכיבי הפרופיל האישיותי שלך. נציין את הכישורים הבולטים שלך על מנת להעמיק את ההיכרות שלך עם עצמך, ובכדי שתדע למנף את העוצמות במקומות הנכונים ולשפר את התחומים החלשים שלך.
        '''פרק הנטיות התעסוקתיות - בפרק זה נציג כיצד הפרופיל האישי שלך מתאים לעולם התעסוקה באמצעות הנטיות התעסוקתיות שלך. את עולם התעסוקה אנחנו מחלקים לשמונה שדות עליהם נפרט בהמשך.
        '''פרק הלי [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property echhechanti() As String
            Get
                Return ResourceManager.GetString("echhechanti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מעבר לעמוד.
        '''</summary>
        Friend Shared ReadOnly Property kishur() As String
            Get
                Return ResourceManager.GetString("kishur", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פרופיל אישיות.
        '''</summary>
        Friend Shared ReadOnly Property list1() As String
            Get
                Return ResourceManager.GetString("list1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to נטיות תעסוקתיות.
        '''</summary>
        Friend Shared ReadOnly Property list2() As String
            Get
                Return ResourceManager.GetString("list2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המלצה לרמת לימוד.
        '''</summary>
        Friend Shared ReadOnly Property list3() As String
            Get
                Return ResourceManager.GetString("list3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המלצה למסלולי לימוד.
        '''</summary>
        Friend Shared ReadOnly Property list4() As String
            Get
                Return ResourceManager.GetString("list4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המלצה למקצועות מתאימים.
        '''</summary>
        Friend Shared ReadOnly Property list5() As String
            Get
                Return ResourceManager.GetString("list5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מה מתקבל בדוח:
        '''חמשת התכונות הבולטות שלך.
        '''מפת התכונות המצטיינות והבולטות שלך וגם התכונות הפחות בולטות שלך.
        '''מפת הנטיות התעסוקתיות שלך.
        '''סוג הלימודים המתאים ביותר עבורך.
        '''מסלולי הלימוד המתאימים לך ביותר, איפה הם נלמדים ומהם תנאי הקבלה.
        '''תחום העיסוק המתאים ביותר עבורך.
        '''המקצוע שיביא לידי ביטוי בצורה הטובה ביותר את האיכויות שלך..
        '''</summary>
        Friend Shared ReadOnly Property mabadoch() As String
            Get
                Return ResourceManager.GetString("mabadoch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פרופיל אישיות.
        '''</summary>
        Friend Shared ReadOnly Property mainBookmark() As String
            Get
                Return ResourceManager.GetString("mainBookmark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המשך פרק התעסוקה.
        '''</summary>
        Friend Shared ReadOnly Property page11HemshechTaasuka() As String
            Get
                Return ResourceManager.GetString("page11HemshechTaasuka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטבלה זו נפרט את המלצות התעסוקה הטובות ביותר עבורך שסוכמו על ידי יועץ המערכת.
        '''</summary>
        Friend Shared ReadOnly Property page11Hesber() As String
            Get
                Return ResourceManager.GetString("page11Hesber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטבלה זו נפרט את בחירותיך האישיות כפי שסומנו בהעדפותיך האישיות.
        '''</summary>
        Friend Shared ReadOnly Property page12Hesber() As String
            Get
                Return ResourceManager.GetString("page12Hesber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מערכת YOUA פותחה על ידי רענן הס ואנשי הצוות שלו כמערכת online לייעוץ קריירה.
        '''המערכת משלבת ידע מתקדם מתחום הפסיכולוגיה יחד עם טכנולוגיה עדכנית, ומאפשרת לכל מי שעונה על השאלון לקבל הכוונה ללימודים ו/או לעבודה באופן מיידי.
        '''שאלון ההתאמה האישית לקריירה, לימודים ותעסוקה מתבסס על מודלים תיאורטיים מתקדמים ועל ניסיון רב שנים בייעוץ תעסוקתי לצעירים בשלב התחלת הקריירה ולמבוגרים לקראת החלטות על קריירה שנייה..
        '''</summary>
        Friend Shared ReadOnly Property page2() As String
            Get
                Return ResourceManager.GetString("page2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הסבר - מה מתקבל בדוח.
        '''</summary>
        Friend Shared ReadOnly Property page2Header() As String
            Get
                Return ResourceManager.GetString("page2Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תיאור קצר לסוגי הטיפוסים על פי רשימת הטיפוסים של נאסא:.
        '''</summary>
        Friend Shared ReadOnly Property page4cont1() As String
            Get
                Return ResourceManager.GetString("page4cont1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אנחנו מחלקים את עולם התעסוקה לשמונה שדות, כאשר כל המקצועות הקיימים כיום משוייכים לשדות אלו.  בעבר נהגו לחלק את עולם התעסוקה לשש שדות, אך עם השנים התפתחו סוגי מקצועות נוספים. לכל שדה יש את המאפיינים שלו..
        '''</summary>
        Friend Shared ReadOnly Property page4header() As String
            Get
                Return ResourceManager.GetString("page4header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס אנשים.
        '''</summary>
        Friend Shared ReadOnly Property page4tipusAnashim1() As String
            Get
                Return ResourceManager.GetString("page4tipusAnashim1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס חברתי, אוהב להימצא בחברת אנשים. הוא חם ולבבי וקושר במהירות קשרים רגשיים עם אנשים מסביבו. מגלה רגישות, התחשבות וסבלנות כלפי אנשים אחרים..
        '''</summary>
        Friend Shared ReadOnly Property page4tipusAnashim2() As String
            Get
                Return ResourceManager.GetString("page4tipusAnashim2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס חוץ וסביבה.
        '''</summary>
        Friend Shared ReadOnly Property page4tipusChutz1() As String
            Get
                Return ResourceManager.GetString("page4tipusChutz1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס דינאמי המעדיף להימצא בניידות ותנועה מאשר לשבת במקום אחד. פעלתן וביצועיסט. אינו אוהב להימצא במקומות סגורים ומעדיף שהייה בחוץ ובטבע..
        '''</summary>
        Friend Shared ReadOnly Property page4tipusChutz2() As String
            Get
                Return ResourceManager.GetString("page4tipusChutz2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס ארגון וסדר.
        '''</summary>
        Friend Shared ReadOnly Property page4tipusEirgun1() As String
            Get
                Return ResourceManager.GetString("page4tipusEirgun1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס יציב ומאופק, סולידי, מסודר, שיטתי וממושמע. בעל כושר התמדה, אחראי וניתן לסמוך עליו..
        '''</summary>
        Friend Shared ReadOnly Property page4tipusEirgun2() As String
            Get
                Return ResourceManager.GetString("page4tipusEirgun2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס עסקי.
        '''</summary>
        Friend Shared ReadOnly Property page4tipusEiski1() As String
            Get
                Return ResourceManager.GetString("page4tipusEiski1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס מעשי ודינאמי, ממולח, בעל כושר שכנוע ויכולת לנהל משא ומתן עם אנשים. אחראי וניתן לסמוך עליו..
        '''</summary>
        Friend Shared ReadOnly Property page4tipusEiski2() As String
            Get
                Return ResourceManager.GetString("page4tipusEiski2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס מדעי.
        '''</summary>
        Friend Shared ReadOnly Property page4tipusMadaei1() As String
            Get
                Return ResourceManager.GetString("page4tipusMadaei1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס המגלה סקרנות לגבי תהליכים בטבע, מתעניין בעיקר בביולוגיה וכימיה. רציונאלי, הגיוני ונבון מאד. הוא שקול ומאופק..
        '''</summary>
        Friend Shared ReadOnly Property page4tipusMadaei2() As String
            Get
                Return ResourceManager.GetString("page4tipusMadaei2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס אומנותי.
        '''</summary>
        Friend Shared ReadOnly Property page4tipusOmanuti1() As String
            Get
                Return ResourceManager.GetString("page4tipusOmanuti1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס מיוחד, &quot;צבעוני&quot;, אינדיבידואליסט ונוטה למרוד במוסכמויות. יצירתי, בעל דמיון ומעוף עשירים ומבטא רגשות בקלות..
        '''</summary>
        Friend Shared ReadOnly Property page4tipusOmanuti2() As String
            Get
                Return ResourceManager.GetString("page4tipusOmanuti2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס תרבותי.
        '''</summary>
        Friend Shared ReadOnly Property page4tipusTarbuti1() As String
            Get
                Return ResourceManager.GetString("page4tipusTarbuti1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס המגלה סקרנות אינטלקטואלית בעיקר בנושאים כמו פילוסופיה, היסטוריה, פולקלור וכדומה. נהנה לקרוא ומסוגל לספר בצורה מעניינת על נושאים בהם מתמצא..
        '''</summary>
        Friend Shared ReadOnly Property page4tipusTarbuti2() As String
            Get
                Return ResourceManager.GetString("page4tipusTarbuti2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס טכנולוגי.
        '''</summary>
        Friend Shared ReadOnly Property page4tipusTech1() As String
            Get
                Return ResourceManager.GetString("page4tipusTech1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טיפוס רציונאלי והגיוני. בעל חוש טכני מפותח, ביצועיסט, מדעי ותכליתי. נהנה להתעסק בתכנון ובתיקון מכשירים..
        '''</summary>
        Friend Shared ReadOnly Property page4tipusTech2() As String
            Get
                Return ResourceManager.GetString("page4tipusTech2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מגלה נטייה ללמוד ולעסוק במקצועות שיש בהם דגש על רווחת האדם - בשדה זה נכללים מקצועות המשרתים צרכים של אנשים אחרים ומתן סעד ושירותים לפי  צורכיהם, כגון: מקצועות הייעוץ, הפסיכולוגיה, ועבודה סוציאלית, וכן מקצועות שירותי הבית והגנה על הפרט והציבור. מטרת העובד היא להגדיל את הרווחה ואיכות החיים של הזולת.
        '''</summary>
        Friend Shared ReadOnly Property page5Anashim() As String
            Get
                Return ResourceManager.GetString("page5Anashim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מגלה נטייה ללמוד ולעסוק במקצועות שיש בהם דגש על כסף - בשדה זה נכללים מקצועות המכירה למיניהם, מסחר בציוד וברכוש, כולל ניירות ערך, מקצועות שקשורים בכלכלה, השקעות ותיווך, ומקצועות של סוכני ביניים במכירה ובקנייה. מטר העובד בשדה זה היא להגדיל את רווחיו האישיים ו/או של רווחי הארגון, והשירות הניתן הוא בבחינת השקעה עתידית להגדלת הרווחים.
        '''</summary>
        Friend Shared ReadOnly Property page5Asakim() As String
            Get
                Return ResourceManager.GetString("page5Asakim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מגלה נטייה ללמוד ולעסוק במקצועות שיש בהם דגש על נוכחות בחוץ - בשדה זה נכללים מדעי הסביבה, חקלאות, דיג, יערנות, גיאולוגיה, מכרות, טיפול בבעלי חיים וספורט. מטרת העובד במקצועות אלו היא לעבד, לשמר ולאסוף את היבול של מקורות המים, הבריכות ואוצרות הטבע למיניהם.
        '''</summary>
        Friend Shared ReadOnly Property page5Chutz() As String
            Get
                Return ResourceManager.GetString("page5Chutz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הנטיות התעוסקתיות של.
        '''</summary>
        Friend Shared ReadOnly Property page5Hanetiyot() As String
            Get
                Return ResourceManager.GetString("page5Hanetiyot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to כאן מוצגות הנטיות התעסוקתיות האישיות שלך, בהדגשת השדות הדומיננטיים באישיותך. מתוך שדות אלו והשילוב ביניהם נגזרת המלצתנו למסלולי הלימוד והתעסוקה עבורך.
        '''</summary>
        Friend Shared ReadOnly Property page5header() As String
            Get
                Return ResourceManager.GetString("page5header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מגלה נטייה ללמוד ולעסוק במקצועות שיש בהם דגש על חקר להבנת הטבע - בשדה זה נכללים מקצועות מדעי הטבע העוסקים בתיאוריה המדעית וביישומים הלא טכנולוגיים שלה. מטרת העובד במקצועות אלו היא להבין את החוקים במגעי הטבע בתחומים: ביולוגיה, כימיה, פיסיקה וכדומה וליישם חוקים אלו.
        '''</summary>
        Friend Shared ReadOnly Property page5Mada() As String
            Get
                Return ResourceManager.GetString("page5Mada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מגלה נטייה ללמוד ולעסוק במקצועות שיש בהם דגש על יצירה אמנותית - בשדה זה נכללים המקצועות הנוגעים בכישרונות מיוחדים בשדה האמנות היוצרת, כגון: ציור, פיסול,  וכן בשדה האמנות המעשית, כגון: עיצוב, אדריכלות, תחום הבידור, ריקוד.  במקצועות אלו מטרת העובד היא להגיע לביצוע נאה של המשימה המוטלת עליו או שהוא נוטל על עצמו.
        '''</summary>
        Friend Shared ReadOnly Property page5Omanut() As String
            Get
                Return ResourceManager.GetString("page5Omanut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ארגון- רמת התאמה .
        '''</summary>
        Friend Shared ReadOnly Property page5sadot1() As String
            Get
                Return ResourceManager.GetString("page5sadot1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טכנולוגיה - רמת התאמה.
        '''</summary>
        Friend Shared ReadOnly Property page5sadot2() As String
            Get
                Return ResourceManager.GetString("page5sadot2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עסקים- רמת התאמה.
        '''</summary>
        Friend Shared ReadOnly Property page5sadot3() As String
            Get
                Return ResourceManager.GetString("page5sadot3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אמנות- רמת התאמה.
        '''</summary>
        Friend Shared ReadOnly Property page5sadot4() As String
            Get
                Return ResourceManager.GetString("page5sadot4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תרבות- רמת התאמה.
        '''</summary>
        Friend Shared ReadOnly Property page5sadot5() As String
            Get
                Return ResourceManager.GetString("page5sadot5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אנשים- רמת התאמה.
        '''</summary>
        Friend Shared ReadOnly Property page5sadot6() As String
            Get
                Return ResourceManager.GetString("page5sadot6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מדע- רמת התאמה.
        '''</summary>
        Friend Shared ReadOnly Property page5sadot7() As String
            Get
                Return ResourceManager.GetString("page5sadot7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חוץ- רמת התאמה.
        '''</summary>
        Friend Shared ReadOnly Property page5sadot8() As String
            Get
                Return ResourceManager.GetString("page5sadot8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מגלה נטייה ללמוד ולעסוק במקצועות שיש בהם דגש על ערכים וידע - בשדה זה נכללים מקצועות המשמרים את ערכי התרבות ואת העברתם מדור לדור, כגון: מדעי הרוח, מדעי החברה, משפטים, עיתונאות, חינוך ,הוראה והדרכה.
        '''</summary>
        Friend Shared ReadOnly Property page5Tarbut() As String
            Get
                Return ResourceManager.GetString("page5Tarbut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מגלה נטייה ללמוד ולעסוק במקצועות שיש בהם דגש על ציוד, מכשירים, מכונות ומבנים - בשדה זה נכללים המקצועות הכרוכים בתכנון, בייצור, באחזקה או במחקר טכנולוגי. כלולים בו מקצועות ההנדסה למיניהם: הנדסת מכונות, הנדסת חשמל, הנדסת חלל וכדומה, ומקצועות התפעול והתיקון של מכשירים ומכונות.
        '''</summary>
        Friend Shared ReadOnly Property page5Tech() As String
            Get
                Return ResourceManager.GetString("page5Tech", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מגלה נטייה ללמוד ולעסוק במקצועות שיש בהם דגש על סדר - בשדה זה נכללים עיסוקי ניהול, מינהל, אדמיניסטרציה ופקידות בעסקים פרטיים, בממשלה, במוסדות ציבוריים, מוניציפאליים ובמפעלים. מטרת העובד היא להפעיל ו/או לפעול למען ארגון וניהול יעילים בהקשר של אנשים, ציוד או נתונים.
        '''</summary>
        Friend Shared ReadOnly Property page5Yrgun() As String
            Get
                Return ResourceManager.GetString("page5Yrgun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ההתאמה האישית של .
        '''</summary>
        Friend Shared ReadOnly Property page6cont1() As String
            Get
                Return ResourceManager.GetString("page6cont1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to נטיות תעסוקתיות.
        '''</summary>
        Friend Shared ReadOnly Property page6cont2() As String
            Get
                Return ResourceManager.GetString("page6cont2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to רמת לימוד מתאימה.
        '''</summary>
        Friend Shared ReadOnly Property page6cont3() As String
            Get
                Return ResourceManager.GetString("page6cont3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פירוט הנטיות התעסוקתיות שלך עבור כל אחד מהשדות הקיימים.
        '''</summary>
        Friend Shared ReadOnly Property page6cont4beforeGraph() As String
            Get
                Return ResourceManager.GetString("page6cont4beforeGraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בשלב הראשון אנו בוחנים מהי רמת הלימוד הנכונה ביותר עבורך. אנו מחלקים את סוגי ההכשרה והלימוד לשלוש רמות לימוד כמפורט בגרף למטה. על פי ההתאמה האישית נמליץ על מסלולי לימוד מתאימים..
        '''</summary>
        Friend Shared ReadOnly Property page6header() As String
            Get
                Return ResourceManager.GetString("page6header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לימודים ברמה אקדמאית - מקצועות שדורשים הכשרה תיאורטית ארוכה.
        '''</summary>
        Friend Shared ReadOnly Property page6Ramatlimud1() As String
            Get
                Return ResourceManager.GetString("page6Ramatlimud1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לימודים ברמה על תיכונית - מקצועות מעשיים הדורשים הכשרה תיאורטית.
        '''</summary>
        Friend Shared ReadOnly Property page6Ramatlimud2() As String
            Get
                Return ResourceManager.GetString("page6Ramatlimud2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לימודים ברמת קורסים מקצועיים - מקצועות מעשיים ותכליתיים הדורשים הכשרה קצרה.
        '''</summary>
        Friend Shared ReadOnly Property page6Ramatlimud3() As String
            Get
                Return ResourceManager.GetString("page6Ramatlimud3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עיסוקים ברמה זו דורשים בדרך כלל השכלה גבוהה, ידע תיאורטי מעמיק ומומחיות רבה. לדוגמא: מקצועות אקדמאים ומהנדסים.
        '''</summary>
        Friend Shared ReadOnly Property page6Ramatlimudperut1() As String
            Get
                Return ResourceManager.GetString("page6Ramatlimudperut1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עיסוקים ברמה זו דורשים בדרך כלל השכלה על תיכונית ויכולת לבצע משימות על בסיס ידע תיאורטי בסיסי והנחיות כלליות בלבד. לדוגמא: הנדסאים וטכנאים.
        '''</summary>
        Friend Shared ReadOnly Property page6Ramatlimudperut2() As String
            Get
                Return ResourceManager.GetString("page6Ramatlimudperut2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עיסוקים ברמה זו דורשים הכשרה מקצועית, מעשית וממוקדת המחייבת מיומנות גבוהה כ&quot;בעל מקצוע&quot;. לדוגמא: מגשר, טכנאי רנטגן, טכנאי תקשורת.
        '''</summary>
        Friend Shared ReadOnly Property page6Ramatlimudperut3() As String
            Get
                Return ResourceManager.GetString("page6Ramatlimudperut3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מוסד לימודים.
        '''</summary>
        Friend Shared ReadOnly Property page7Chart1() As String
            Get
                Return ResourceManager.GetString("page7Chart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מסלול לימודים.
        '''</summary>
        Friend Shared ReadOnly Property page7Chart2() As String
            Get
                Return ResourceManager.GetString("page7Chart2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סוג לימודים.
        '''</summary>
        Friend Shared ReadOnly Property page7Chart3() As String
            Get
                Return ResourceManager.GetString("page7Chart3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אחוזי התאמה.
        '''</summary>
        Friend Shared ReadOnly Property page7Chart4() As String
            Get
                Return ResourceManager.GetString("page7Chart4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חמשת מסלולי הלימוד המתאימים ביותר עבורך.
        '''</summary>
        Friend Shared ReadOnly Property page7ChartHeader() As String
            Get
                Return ResourceManager.GetString("page7ChartHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מסלולי הלימוד המתאימים מבוססים על תוצאות האבחון ועל העדפותיך האישיות .
        '''</summary>
        Friend Shared ReadOnly Property page7cont() As String
            Get
                Return ResourceManager.GetString("page7cont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המשך פרק הלימודים.
        '''</summary>
        Friend Shared ReadOnly Property page7hemshechLimudim() As String
            Get
                Return ResourceManager.GetString("page7hemshechLimudim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטבלה זו נפרט את חמשת מסלולי הלימוד שנבחרו בעבורך על ידי היועץ .
        '''</summary>
        Friend Shared ReadOnly Property page7Hesber() As String
            Get
                Return ResourceManager.GetString("page7Hesber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטבלה זו נפרט את המלצות הלימודים הטובות ביותר עבורך שסוכמו על ידי יועץ המערכת .
        '''</summary>
        Friend Shared ReadOnly Property page8Header1() As String
            Get
                Return ResourceManager.GetString("page8Header1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטבלה זו נפרט את בחירותיך האישיות כפי שסומנו בהעדפותיך האישיות.
        '''</summary>
        Friend Shared ReadOnly Property page8Header2() As String
            Get
                Return ResourceManager.GetString("page8Header2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטבלה זו נפרט עד עשר המלצות מערכת הטובות ביותר עבורך.
        '''</summary>
        Friend Shared ReadOnly Property page9Header() As String
            Get
                Return ResourceManager.GetString("page9Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פרק הלימודים.
        '''</summary>
        Friend Shared ReadOnly Property perekHalimudim() As String
            Get
                Return ResourceManager.GetString("perekHalimudim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פרק התעסוקה.
        '''</summary>
        Friend Shared ReadOnly Property perekHataasuka() As String
            Get
                Return ResourceManager.GetString("perekHataasuka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מקצוע.
        '''</summary>
        Friend Shared ReadOnly Property perekHataasukaChart1() As String
            Get
                Return ResourceManager.GetString("perekHataasukaChart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to איפה לומדים.
        '''</summary>
        Friend Shared ReadOnly Property perekHataasukaChart2() As String
            Get
                Return ResourceManager.GetString("perekHataasukaChart2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מסלול לימודים נדרש.
        '''</summary>
        Friend Shared ReadOnly Property perekHataasukaChart3() As String
            Get
                Return ResourceManager.GetString("perekHataasukaChart3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטבלה זו נפרט את חמשת המקצועות שנבחרו בעבורך על ידי היועץ.
        '''</summary>
        Friend Shared ReadOnly Property perekHataasukaCont() As String
            Get
                Return ResourceManager.GetString("perekHataasukaCont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ההמלצות שלנו למסלולי התעסוקה המתאימים מבוססים על תוצאות האבחון ועל העדפותיך האישיות, ומסלולי ההכשרה אותם סימנו עבורך בפרק הלימודים.
        '''</summary>
        Friend Shared ReadOnly Property perekHataasukaCont1() As String
            Get
                Return ResourceManager.GetString("perekHataasukaCont1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עשר המלצות המערכת הטובות ביותר עבורך.
        '''</summary>
        Friend Shared ReadOnly Property perekHataasukaCont2() As String
            Get
                Return ResourceManager.GetString("perekHataasukaCont2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הפרק האישיותי של .
        '''</summary>
        Friend Shared ReadOnly Property perekishiyut() As String
            Get
                Return ResourceManager.GetString("perekishiyut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אני ממליץ להבין ולהכיר את הסעיפים הבאים לעומק, כי שימוש נכון ביכולות ובחוזקות שלך יוביל אותך למקומות טובים ונכונים.
        '''</summary>
        Friend Shared ReadOnly Property perekishiyut1() As String
            Get
                Return ResourceManager.GetString("perekishiyut1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מאפייני האישיות הבולטים של.
        '''</summary>
        Friend Shared ReadOnly Property perekishiyut2() As String
            Get
                Return ResourceManager.GetString("perekishiyut2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סיכום וקצת צידה לדרך.
        '''</summary>
        Friend Shared ReadOnly Property sicum() As String
            Get
                Return ResourceManager.GetString("sicum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אחד מהציטוטים האהובים עלי הוא של סטיב ג&apos;ובס כאשר ניסה לתמצת את המפתח את המפתח להצלחה בחיים ואמר .
        '''</summary>
        Friend Shared ReadOnly Property sicumCont1() As String
            Get
                Return ResourceManager.GetString("sicumCont1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;Do what you love&quot;.
        '''</summary>
        Friend Shared ReadOnly Property sicumCont2() As String
            Get
                Return ResourceManager.GetString("sicumCont2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אני מאמין שאם נפנה ונעסוק במה שאנחנו אוהבים - כך גם נצליח. הצלחה זו תשפיע על שאר המימדים בחיים שלנו ותצעיד אותנו קדימה לכיווני התפתחות נכונים..
        '''</summary>
        Friend Shared ReadOnly Property sicumCont3() As String
            Get
                Return ResourceManager.GetString("sicumCont3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התכנית שבנינו לך היא השלב הראשון ביציאה לדרך החדשה ובה תשובות, כלים וכיוונים. נותר לקחת את כל הכלים ולצאת לדרך..
        '''</summary>
        Friend Shared ReadOnly Property sicumCont4() As String
            Get
                Return ResourceManager.GetString("sicumCont4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to נכון שיהיו קשיים, ולא תמיד הכול פשוט מול הלחצים שבדרך, ציפיות הסביבה, הצורך לרצות אחרים ועמידה בציפיות הסביבה שיאתגרו כל הזמן את ההיצמדות לתכנית הזו..
        '''</summary>
        Friend Shared ReadOnly Property sicumCont5() As String
            Get
                Return ResourceManager.GetString("sicumCont5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ככל שיהיו בך הכוחות וההבנה להיצמד לכיוון אותו בחרת, כך יגיעו גם ההצלחות, והן יגיעו..
        '''</summary>
        Friend Shared ReadOnly Property sicumCont6() As String
            Get
                Return ResourceManager.GetString("sicumCont6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אאחל לך המון בהצלחה.
        '''</summary>
        Friend Shared ReadOnly Property sicumCont7() As String
            Get
                Return ResourceManager.GetString("sicumCont7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  YOUA רענן הס, פסיכולוג ראשי.
        '''</summary>
        Friend Shared ReadOnly Property sicumCont8() As String
            Get
                Return ResourceManager.GetString("sicumCont8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מקצוע.
        '''</summary>
        Friend Shared ReadOnly Property tavlaTaasuka1() As String
            Get
                Return ResourceManager.GetString("tavlaTaasuka1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to איפה לומדים.
        '''</summary>
        Friend Shared ReadOnly Property tavlaTaasuka2() As String
            Get
                Return ResourceManager.GetString("tavlaTaasuka2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מסלול לימודים נדרש.
        '''</summary>
        Friend Shared ReadOnly Property tavlaTaasuka3() As String
            Get
                Return ResourceManager.GetString("tavlaTaasuka3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אדם אשר מחובר לעשייה, להנעת תהליכים, שאוהב לאתגר את עצמו בפרוייקטים חדשים וביוזמות שונות. מניע בעצמו תהליך או מאיץ תהליך. נוטה שלא לחשוש משינויים ויודע לאתר הזדמנויות.
        '''</summary>
        Friend Shared ReadOnly Property tipusYazami() As String
            Get
                Return ResourceManager.GetString("tipusYazami", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
